#create the Pod without namespace
apiVersion: v1
kind: Pod
metadata:
  name: nodejsapp
spec:
  containers:
  - name: nodejsapp
    image: gbalakrishna/nodejsapp:v1
    ports:
    - containerPort: 3000
    
