---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv1
  labels:
    type: ebs-pv1
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-04180df2e5277b4ea
    fsType: ext4



