apiVersion: v1
kind: Service
metadata:
  name: hostpathService
  labels:
    app: nginx   
spec:
  type: NodePort
  selector:
   app: hostpath
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010