---
apiVersion: v1
kind: Namespace
metadata:
  name: pythonapp
  labels:
    app: pythonapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonappblue
  namespace: pythonapp 
  labels:
    app: pythonapp
    version: v1
    color: blue
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
      version: v1
      color: blue 
  template:
    metadata:
      labels:
        app: pythonapp
        version: v1
        color: blue        
    spec:
      containers:
      - name: pythonapp
        image: gbalakrishna/pythonapp:v1
        ports:
        - containerPort: 5000
...        

