---
apiVersion: v1
kind: Service
metadata:
  name: pythonappblue
  namespace: pythonapp
  labels:
    app: pythonapp  
spec:
  type: NodePort
  selector:
    version: v1
  ports:
    - port: 8090
      targetPort: 5000
      nodePort: 30007
...  

