---
apiVersion: v1
kind: Service
metadata:
  name: pythonappgreen
  namespace: pythonapp
  labels:
    app: pythonapp  
spec:
  type: NodePort
  selector:
    version: v2
  ports:
    - port: 8080
      targetPort: 5000
      nodePort: 30008
...    

