---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejsapp
  labels:
    app: nodejsapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: nodejsapp 
  labels:
    app: nodejsapp
    version: v2
    color: blue
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
        version: v2
        color: blue        
    spec:
      containers:
      - name: nodejsapp
        image: gbalakrishna/pythonapp:v1
        ports:
        - containerPort: 3000
