---
apiVersion: v1
kind: Namespace
metadata:
  name: pythonapp
  labels:
    app: pythonapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonappgreen
  namespace: pythonapp 
  labels:
    app: pythonapp
    version: v2
    color: green
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
      version: v2
      color: green       
  template:
    metadata:
      labels:
        app: pythonapp
        version: v2
        color: green         
    spec:
      containers:
      - name: pythonapp
        image: gbalakrishna/pythonapp:v2
        ports:
        - containerPort: 5000
...
