---
#nodeportwithoutnamespace
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
   labels:
    app: nodejsapp 
  spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8090
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
 ---
#pod
apiVersion: v1
kind: Pod
metadata:
  name: nodejsapp
  labels:
    app: nodejsap  
spec:
  containers:
  - name: nodejsapp
    image: gbalakrishna/nodejsapp:v1
    ports:
    - containerPort: 3000
