apiVersion: v1
kind: Pod
metadata:
  name: test-pd
  labels:
   app: emptydir  
spec:
  containers:
  - image: nginx:1.25.1
    name: test-container
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/run/docker.sock
      # this field is optional
      type: Socket
