---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejsapp
  labels:
    app: nodejsapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  labels:
    app: nodejsapp
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: gbalakrishna/nodejsapp:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: nodejsapp
  labels:
    app: nodejsapp  
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
    - port: 8090
      targetPort: 3000
      nodePort: 30007
...
