apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: emptydir
  template:
    metadata:
      labels:
        app: emptydir  
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: hostpathvole
      volumes:
        - name: hostpathvole
          hostPath:
              path: /tmp/hostpath100ls
              type: Directory 