---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc1
spec:
  storageClassName: awsgp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


      


