apiVersion: v1
kind: Pod
metadata:
  name: ebs-volume-pod
  labels:
    app: ebs-volume-pod
spec:
  volumes:
    - name: ebs-volume-pod
      persistentVolumeClaim:
        claimName: ebs-pvc1
  containers:
    - name: ebs-volume-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: ebs-volume-pod
        - mountPath: "/usr/share/nginx/html"
