---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
   app: test-pod-1
spec:
  volumes:
    - name: task-pv-storage-1
      persistentVolumeClaim:
        claimName: ebs-pvc1
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
       - name: task-pv-storage-1     
         mountPath: "/usr/share/nginx/html"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
   app: test-pod-2
spec:
  volumes:
    - name: task-pv-storage-2
      persistentVolumeClaim:
        claimName: ebs-pvc2
  containers:
    - name: task-pv-container
      image: gbalakrishna/balautils:v1
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
       - name: task-pv-storage-2     
         mountPath: "/usr/share/nginx/html"   
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  labels:
   app: test-pod-3
spec:
  volumes:
    - name: task-pv-storage-2
      persistentVolumeClaim:
        claimName: ebs-pvc2
  containers:
    - name: task-pv-container
      image: gbalakrishna/balautils:v2
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
       - name: task-pv-storage-2     
         mountPath: "/usr/share/nginx/html"      