---
apiVersion: v1
kind: Service
metadata:
  name: hostpathService
  labels:
    app: nginx   
spec:
  type: NodePort
  selector:
      app: test-pod-1
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30010
---      
apiVersion: v1
kind: Service
metadata:
  name: hostpathService
  labels:
    app: nginx   
spec:
  type: NodePort
  selector:
      app: test-pod-2
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30011     
---
apiVersion: v1
kind: Service
metadata:
  name: hostpathService
  labels:
    app: nginx   
spec:
  type: NodePort
  selector:
      app: test-pod-3
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30012          