---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod1
    image: sreeharshav/rollingupdate:v1
    volumeMounts:
      - name: testvol
        mountPath: /tmp/testvolume
  - name: mypod2
    image: sreeharshav/utils
    volumeMounts:
      - name: testvol
        mountPath: /tmp/data
  volumes:
     - name: testvol
       hostPath:
          path: /tmp/
          type: Directory
  nodeSelector:
      kubernetes.io/hostname: ip-172-20-52-2.ec2.internal
