apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim01
spec:
  storageClassName: local-storage-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi  
---       
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim03
spec:
  storageClassName: local-storage-02
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi 