apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskpvdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      name: task-pv-pod
      labels:
        app: nginx   
    spec:    
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim01 
      containers:
        - name: task-pv-container
          image: nginx
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskpvdeploy2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      name: task-pv-pod
      labels:
        app: nginx   
    spec:    
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim02
      containers:
        - name: task-pv-container
          image: nginx
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: task-pv-storage