apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
  labels: 
     name: raw-volume-testing
spec:
  containers:
  - image: nginx
    name: nginxpod
    imagePullPolicy: Always
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    awsElasticBlockStore:
       volumeID: vol-0755d708d698d035a
       fsType: ext4
  nodeSelector:
    kubernetes.io/hostname: ip-172-20-76-92.ec2.internal
