apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
   app: hostpath  
spec:
  containers:
  - image: nginx:1.25.1
    name: hostpath-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/hostpath
      # this field is optional
      type: Directory 